/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/page/IframeElement.lh
 */
export class IframeElementRTBase extends Laya.Box {
    public videoBtn!: Laya.Button;
    public closeBox!: Laya.Box;
    public iframeBox!: Laya.Box;
}

