/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/list/MailList.lh
 */
export class MailListRTBase extends Laya.Box {
    public addMail!: Laya.Button;
    public selectDel!: Laya.Button;
    public selectFlag!: Laya.Button;
    public mailList!: Laya.List;
}

