/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/useUI/ChangeTexture.lh
 */
export class ChangeTextureRTBase extends Laya.Box {
    public spImg!: Laya.Sprite;
    public Img!: Laya.Image;
    public textureImg!: Laya.Sprite;
    public fillTexture!: Laya.Sprite;
}

