/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * scenes/Index.ls
 */
export class IndexRTBase extends Laya.Scene {
    public uiBtn!: Laya.Box;
    public phyBtn!: Laya.Box;
    public d3Btn!: Laya.Box;
}

