/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */


/**
 * prefab/uiDemo/animation/AtlasAni.lh
 */
export class AtlasAniRTBase extends Laya.Box {
    public playAni!: Laya.Button;
    public stopAni!: Laya.Button;
    public selectAni!: Laya.ComboBox;
    public aniSource!: Laya.Animation;
}

